#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.9.6

pipelines:
  default:
    -  parallel:
        - step:
            name: Build and Test
            caches:
              - maven
            script:
              - docker-compose -f docker-compose.yml up
              - mvn clean test
              - docker-compose -f docker-compose.yml down
            artifacts:
              - target/HtmlReports/**
            services:
              - chrome
definitions:
  services:
    chrome:
      image: selenium/standalone-chrome