image: maven:3.9.6

pipelines:
  default:
    - step:
        size: 2x # Total memory is 8GB
        name: Run Selenium Tests
        caches:
          - maven
        services:
          - selenium-hub
          - chrome
          - chrome-1
          - chrome-2
        script:
          - mvn clean test
definitions:
  services:
    selenium-hub:
      image: selenium/hub:4.19.1-20240402
      memory: 2048

      variables:
        SE_EVENT_BUS_HOST: "127.0.0.1"
    chrome:
      image: selenium/node-chrome:4.19.1-20240402
      memory: 2048
      variables:
        SE_EVENT_BUS_HOST: "127.0.0.1"
        SE_EVENT_BUS_PUBLISH_PORT: "4442"
        SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
    chrome-1:
      image: selenium/node-chrome:4.19.1-20240402
      memory: 2048
      variables:
        SE_EVENT_BUS_HOST: "127.0.0.1"
        SE_EVENT_BUS_PUBLISH_PORT: "4442"
        SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
    chrome-2:
      image: selenium/node-chrome:4.19.1-20240402
      memory: 2048
      variables:
        SE_EVENT_BUS_HOST: "127.0.0.1"
        SE_EVENT_BUS_PUBLISH_PORT: "4442"
        SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"