image: maven:3.9.6

pipelines:
  default:
    - step:
        name: Run Selenium Tests
        caches:
          - maven
        services:
          - name: selenium/hub:4.19.1-20240402
            alias: selenium-hub
          - name: selenium/node-chrome:4.19.1-20240402
            alias: chrome
        script:
          - mvn clean test